### ISSUE TITLE
Not working in IntelliJ 2021.3

### ISSUE THREAD

**Issue by Saduff** [bestv5/CodeGlance#10]
* IntelliJ: 2021.3 Build #IU-213.5744.223, built on November 27, 2021
* Plugin: 2.1.1-2021.1.3

No errors, but minimap does not show.

---

Update: seems like it doesn't work only for Markdown (.md) files.

**Comment by jerry1970** [comment]
I was having a lot of problems getting it started after the latest update (both PHPStorm and Rider). Went back to CodeGlance 2 for a while but now that stopped. Now back to Code Glance 3, and indeed, it seems to work but not for .MD files. I use MD files a lot so I hope this can be solved.

**Comment by Saduff** [comment]
There's a new plugin that works: https://plugins.jetbrains.com/plugin/18824-codeglance-pro

Closing in favor of https://github.com/bestv5/CodeGlance/issues/12
